### ISSUE TITLE
Add WalletConnect support to wallet - 3000$ worth of G$s

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/Bounties#10]
### Motivation

Easily use the G$ wallet with other DEFI projects, specifically on FUSE.

### Details
- [x] ability to scan/paste walletconnect QR code/link and perform the connection
- [ ] deeplinks or other integration for react-native/mobile version of the GoodDAPP
- [x] a screen to confirm signatures/transactions. for verified contracts show the method and params which are being executed
   - [x] read contract abi from etherscan/fuse explorer
   - [x] parse tx details and display in human readable format
- [x] implement the UI design given
- [x] pass code review by wallet team
- [x] pass QA by wallet team
- [x] write a short article to be published publicly about the dev experience/tutorial
- [ ] support bug fixing for 2 weeks
- [ ] deliver in 1 month after starting work
https://developer.trustwallet.com/wallet-connect

**Comment by iheanyi1** [comment]
Is this issue resolved. I saw it on dework and i will like to tackle it
