### ISSUE TITLE
Use Formik and Yup to validate forms and data over the whole app - 2K USD worth of G$s 

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/Bounties#16]
### Motivation

We're performing manually:

- form validation

As a result:

- we had duplicated/similar code
- connection to the forms is still performed manually
- it has been refactored as much as it was possible but still doesn't looks fine

### Goals

1. To have unified validation in forms
2. To apply validations to the forms easily in automatic mode (without handling change events, writing own hooks etc)

### Solution

To use formik for validation.

1. On form level `formik` should be used. together with the `yup` schemas
2. Current validation logic should be concentrated inside validation callback (currently it's splitted per each field).

### Details

- [ ] make sure our every custom field component has `onChangeText` (1onChange`) and `onBlur` props **2h**
- [ ] create custom validated component 
  - [ ] accept custom jsx rendering field and error dislkay as children **2h**
  - [ ] try to avoid render function as children by using `useFormikContext` **2h**
  - [ ] use `<Field>` component **2h**
  - [ ] to pass down `onChange`, `onBlur`,value, error etc **2h**
  - [ ] `name` prop should recall handleChange, handleBlur from the formik context **2h**
- [ ] create HoC wrapping any our custom field with validation and some default error display **2h**
- [ ] create and export validated field components (using HoC or custom component if we need some custom render for particular field) **4h**
- [ ] create basic validated form accepting schema and custom jsx 
  - [ ] should accept jsx as `children` **2h**
  - [ ] should accept `data` (as initial values) **2h**
  - [ ] should accept validation callback fn **2h**
  - [ ] add custom submit component using `CustomButton` and `useFormikContext` **4h**
  - [ ] add imperative handle to call submit from outside **2h**
- [ ] add validation to forms
  - [ ] validate user forms **4h**
  - [ ] validate signup forms **4h**
  - [ ] validate send / receive forms **2h**
  - [ ] look up the whole app and validate the other forms we have **4h**

**~44h total**

**Comment by visitskyworld** [comment]
@johnsmith-gooddollar , I am interested in completing this issue.

**Comment by johnsmith-gooddollar** [comment]
@visitskyworld Okay, we need to estimate the final bounty value in G$.
I will update You once we'll do it, ad of course we will update the task's description

**Comment by johnsmith-gooddollar** [comment]
@visitskyworld we're still discussing this task. We agreed to remove validation schemas, but there's a few questions to talk about. 

I'll update You tomorrow please wait

**Comment by visitskyworld** [comment]
Should I start work from now or are you going to create a bounty to gitcoin?

**Comment by johnsmith-gooddollar** [comment]
> Should I start work from now or are you going to create a bounty to gitcoin?
Yes you could start work from now. 
First of all - please join https://t.me/gooddollarbounties group
Then add me (https://t.me/johnsmith_gooddollar) and write DM.
You may have questions regarding the task - i'll assist You. 
I'll be available tomorrow from 10-11am EET. Also we could make a call that time

Regarding the gitcoin - @sirpy could you please suggest here ?

**Comment by iheanyi1** [comment]
Hello @johnsmith-gooddollar is this task completed?
