### ISSUE TITLE
Upgrade react-navigation to version 6.x - 500 USD worth of G$s

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/Bounties#17]
### Motivation

Right now the project uses a mix of v4 and v5 for navigation.
Both of them are now **outdated**. Actual version is `react-navigation` v6

This may cause incompatibility issues in the further `react-native` upgrades, which may be needed if we want to support the newest iOS and Android devices.

Last time we had to "play" alot with the deps versions to make the app support Android API Level 30 requiring RN 0.65.x

### Goals

1. To align all `react-navigation` libraries used to version 6.x
2. To have option to keep it up-to-date using just the package manager

#### Upgrade guides

- [4.x -> 5.x](https://reactnavigation.org/docs/5.x/upgrading-from-4.x)
- [5.x -> 6.x](https://reactnavigation.org/docs/upgrading-from-5.x)

#### Key setup points 

- [ ] Uninstall  old react-navigation libraries (native + web) **0.5h**
- [ ] Install new libraries (native + web) **1h**

### Key code changes

- [ ] Replace createAppContainer with NavigationContainer **2h**
- [ ] Replace onNavigationStateChange with onStateChange **2h**
- [ ] update src/components/appNavigation/stackNavigation.js **4h**

### Testing

- [ ] update unit tests (snapshots, mocks etc) **2h**

**~11.5h total**

**Comment by sirpy** [comment]
@johnsmith-gooddollar What should they do about the "key issues known"? how can they reproduce it? when does it happen?

**Comment by johnsmith-gooddollar** [comment]
> @johnsmith-gooddollar What should they do about the "key issues known"? how can they reproduce it? when does it happen?

when i tried to update to 5.x in the previous year i got this runtime error during app startup.

**Comment by ranjithjupaka** [comment]
Hey i want to work on this issue . Please assign this to me.

**Comment by sirpy** [comment]
iceboxed for now
